### ISSUE TITLE
Bug: If an event has disappared during `collapse_event_row` we get an uncaught exception

### ISSUE THREAD

**Issue by hmpf** [Uninett/Howitz#39]
```
2023-11-29 13:23:51,308 ERROR howitz /VENVS/howitz/lib/python3.10/site-packages/flask/app.py:1414:: Exception on /events/163192/collapse_row [GET]
Traceback (most recent call last):
  File "/VENVS/howitz/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/VENVS/howitz/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/VENVS/howitz/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/VENVS/howitz/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/../howitz/src/howitz/endpoints.py", line 303, in collapse_event_row
KeyError: '163192'
```

Disregard the line numbers.

I think the fix is to catch the potential KeyError here:

```
event = create_table_event(current_app.event_manager.create_event_from_id(event_id))
```

Change this to:

```
try:
    plain_event = current_app.event_manager.create_event_from_id(event_id)
except KeyError:
    # DO SOMETHING
    # Return early
event = create_table_event(plain_event)
```

**Comment by hmpf** [comment]
I suspect this is fixed in #19, closing
